# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme
theme: jekyll-theme-cayman
title: Haochen Hu 
description: Haochen Hu, B.S. in Informatics, University of Washington
show_downloads: false
